# Generated by Django 5.2 on 2026-07-13 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets_detudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_awarded', models.CharField(max_length=255)),
                ('award_date', models.DateField()),
                ('certificate_number', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projets_detudes.projetetude')),
            ],
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('heure', models.TimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('statut', models.CharField(blank=True, default='Planifiée', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets_detudes.projetetude')),
                ('responsable_planification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soutenances_planifiees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JuryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('president', 'Président'), ('rapporteur', 'Rapporteur'), ('examinateur', 'Examinateur'), ('directeur', 'Directeur'), ('co_directeur', 'Co-directeur')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jury_created', to=settings.AUTH_USER_MODEL)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_as_enseignant', to=settings.AUTH_USER_MODEL)),
                ('soutenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury', to='soutenance.soutenance')),
            ],
        ),
        migrations.CreateModel(
            name='DeliberationSoutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_finale', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mention', models.CharField(blank=True, max_length=100)),
                ('decision', models.CharField(choices=[('admis', 'Admis'), ('admis_corrections', 'Admis sous réserve de corrections'), ('ajourne', 'Ajourné'), ('rejete', 'Rejeté')], max_length=50)),
                ('observations', models.TextField(blank=True)),
                ('date_deliberation', models.DateTimeField(auto_now_add=True)),
                ('resultat_publie', models.BooleanField(default=False)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('soutenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliberation', to='soutenance.soutenance')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveSoutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('archive_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('soutenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='soutenance.soutenance')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeSoutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directeur_validation', models.BooleanField(default=False)),
                ('responsable_validation', models.BooleanField(default=False)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('observations_directeur', models.TextField(blank=True)),
                ('observations_responsable', models.TextField(blank=True)),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_soutenance', to='projets_detudes.candidate')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets_detudes.projetetude')),
                ('responsable_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_reçues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('projet',), name='unique_demande_soutenance_par_projet')],
            },
        ),
        migrations.AddConstraint(
            model_name='soutenance',
            constraint=models.UniqueConstraint(fields=('projet',), name='unique_soutenance_par_projet'),
        ),
    ]
