# Generated by Django 5.2 on 2026-06-02 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets_detudes', '0008_alter_tache_canevas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeSoutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directeur_validation', models.BooleanField(default=False)),
                ('responsable_validation', models.BooleanField(default=False)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('observations_directeur', models.TextField(blank=True)),
                ('observations_responsable', models.TextField(blank=True)),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_soutenance', to='projets_detudes.candidate')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets_detudes.projetetude')),
                ('responsable_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_reçues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('heure', models.TimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets_detudes.projetetude')),
                ('responsable_planification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soutenances_planifiees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JuryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('president', 'Président'), ('rapporteur', 'Rapporteur'), ('examinateur', 'Examinateur'), ('directeur', 'Directeur'), ('co_directeur', 'Co-directeur')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jury_created', to=settings.AUTH_USER_MODEL)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_as_enseignant', to=settings.AUTH_USER_MODEL)),
                ('soutenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury', to='soutenance.soutenance')),
            ],
        ),
    ]
