# Generated by Django 5.2 on 2026-06-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='statut',
            field=models.CharField(blank=True, default='Planifiée', max_length=50),
        ),
    ]
