# Generated by Django 5.2 on 2026-06-03 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets_detudes', '0008_alter_tache_canevas'),
        ('soutenance', '0002_alter_soutenance_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='demandesoutenance',
            constraint=models.UniqueConstraint(fields=('projet',), name='unique_demande_soutenance_par_projet'),
        ),
        migrations.AddConstraint(
            model_name='soutenance',
            constraint=models.UniqueConstraint(fields=('projet',), name='unique_soutenance_par_projet'),
        ),
    ]
