# Generated by Django 5.2 on 2026-06-04 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets_detudes', '0008_alter_tache_canevas'),
        ('soutenance', '0003_demandesoutenance_unique_demande_soutenance_par_projet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveSoutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('archive_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('soutenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='soutenance.demandesoutenance')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_awarded', models.CharField(max_length=255)),
                ('award_date', models.DateField()),
                ('certificate_number', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projets_detudes.projetetude')),
            ],
        ),
        migrations.CreateModel(
            name='DeliberationSoutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_finale', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mention', models.CharField(blank=True, max_length=100)),
                ('decision', models.CharField(choices=[('admis', 'Admis'), ('admis_corrections', 'Admis sous réserve de corrections'), ('ajourne', 'Ajourné'), ('rejete', 'Rejeté')], max_length=50)),
                ('observations', models.TextField(blank=True)),
                ('date_deliberation', models.DateTimeField(auto_now_add=True)),
                ('resultat_publie', models.BooleanField(default=False)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('soutenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliberation', to='soutenance.demandesoutenance')),
            ],
        ),
    ]
