# Generated by Django 5.2 on 2026-06-04 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenance', '0004_archivesoutenance_award_deliberationsoutenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivesoutenance',
            name='soutenance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='soutenance.soutenance'),
        ),
        migrations.AlterField(
            model_name='deliberationsoutenance',
            name='soutenance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliberation', to='soutenance.soutenance'),
        ),
    ]
