# Generated by Django 5.2 on 2026-06-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenance', '0005_alter_archivesoutenance_soutenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliberationsoutenance',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deliberationsoutenance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
