# Generated by Django 5.2 on 2026-07-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('type_evenement', models.CharField(choices=[('conference', 'Conférence'), ('atelier', 'Atelier')], default='conference', max_length=20, verbose_name="Type d'événement")),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/images/', verbose_name='Image')),
                ('date_evenement', models.DateTimeField(verbose_name="Date de l'événement")),
                ('lieu', models.CharField(blank=True, max_length=255, verbose_name='Lieu')),
                ('lien_inscription', models.URLField(blank=True, verbose_name="Lien d'inscription")),
                ('lien_details', models.URLField(blank=True, verbose_name='Lien détails')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_actif', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'db_table': 'evenement',
                'ordering': ['date_evenement'],
            },
        ),
    ]
