# Generated by Django 5.2 on 2025-06-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('types_document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedocument',
            name='libelle',
            field=models.CharField(max_length=100, verbose_name='Type Document'),
        ),
    ]
