# Generated by Django 5.2 on 2026-07-13 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, max_length=150, null=True, verbose_name='Adresse :')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('niveau', models.CharField(choices=[('master', 'Master'), ('doctorat', 'Doctorat')], max_length=20)),
                ('domaine', models.CharField(max_length=150)),
                ('sujet_recherche', models.TextField(blank=True, null=True)),
                ('annee_inscription', models.DateTimeField(blank=True, null=True)),
                ('orcid', models.CharField(blank=True, max_length=150, null=True, verbose_name='ORCID :')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='accounts', verbose_name='Photo :')),
                ('reseau_social_facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('reseau_social_twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('reseau_social_linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('reseau_social_youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CanevasProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre')),
                ('description', models.TextField()),
                ('canevas_pdf', models.FileField(upload_to='projet_etude/canevas', verbose_name='Fichier')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_projet', models.CharField(choices=[('memoire', 'Mémoire'), ('these', 'Thèse')], max_length=20)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du projet')),
                ('description', models.TextField(verbose_name='Description du projet')),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('en_cours', 'En Cours'), ('en_revue', 'En Revue'), ('valide', 'Valide'), ('termine', 'Termine'), ('rejete', 'Rejete')], default='soumis', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='projets_detudes.candidate')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanningEncadrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_rendez_vous', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('lien_visio', models.URLField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, choices=[('planifie', 'Planifié'), ('effectue', 'Effectué'), ('reporte', 'Reporté'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('observation', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canevas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planings', to='projets_detudes.canevasprojet')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planings', to='projets_detudes.projetetude')),
            ],
            options={
                'ordering': ['date_rendez_vous', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Auteur principal', 'Auteur'), ('Co-auteur', 'Co Auteur'), ('Directeur', 'Directeur'), ('Co-directeur', 'Co Directeur')], max_length=30)),
                ('has_accepted', models.CharField(choices=[('en_attente', 'En Attente'), ('accepte', 'Accepte'), ('refuse', 'Refuse')], default='en_attente', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet', to='projets_detudes.projetetude')),
            ],
        ),
        migrations.AddField(
            model_name='canevasprojet',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canevas', to='projets_detudes.projetetude'),
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('description', models.TextField()),
                ('priorite', models.CharField(blank=True, choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], default='moyenne', max_length=20)),
                ('statut', models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('retard', 'Retard')], default='en_attente', max_length=20)),
                ('progression', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fichier_pdf_tache', models.FileField(blank=True, null=True, upload_to='projet_etude/tache', verbose_name='Fichier')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigne_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tache_assignee', to=settings.AUTH_USER_MODEL)),
                ('canevas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='projets_detudes.canevasprojet')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tache_creee', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='projets_detudes.projetetude')),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
    ]
