# Generated by Django 5.2 on 2026-05-25 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets_detudes', '0002_alter_participant_projet_alter_participant_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('Auteur principal', 'Auteur'), ('Co-auteur', 'Co Auteur'), ('Directeur', 'Directeur'), ('Co-directeur', 'Co Directeur')], max_length=30),
        ),
        migrations.CreateModel(
            name='CanevasProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre')),
                ('description', models.TextField()),
                ('canevas_pdf', models.FileField(upload_to='projet_etude/canevas', verbose_name='Fichier')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canevas', to='projets_detudes.projetetude')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningEncadrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_rendez_vous', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('lien_visio', models.URLField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('effectue', 'Effectué'), ('reporte', 'Reporté'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('observation', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canevas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planings', to='projets_detudes.canevasprojet')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planings', to='projets_detudes.projetetude')),
            ],
            options={
                'ordering': ['date_rendez_vous', 'heure_debut'],
            },
        ),
    ]
