# Generated by Django 5.2 on 2026-05-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets_detudes', '0003_alter_participant_role_canevasprojet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canevasprojet',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
