# Generated by Django 5.2 on 2026-05-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets_detudes', '0004_alter_canevasprojet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningencadrement',
            name='statut',
            field=models.CharField(blank=True, choices=[('planifie', 'Planifié'), ('effectue', 'Effectué'), ('reporte', 'Reporté'), ('annule', 'Annulé')], default='planifie', max_length=20),
        ),
    ]
