# Generated by Django 5.2 on 2026-05-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets_detudes', '0006_tache'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='fichier_pdf_tache',
            field=models.FileField(blank=True, null=True, upload_to='projet_etude/tache', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='progression',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
