# Generated by Django 5.2 on 2026-05-26 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets_detudes', '0007_tache_fichier_pdf_tache_alter_tache_progression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='canevas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='projets_detudes.canevasprojet'),
        ),
    ]
