# Generated by Django 5.2 on 2026-04-09 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_inc', models.CharField(blank=True, editable=False, max_length=25, null=True, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=150, null=True, verbose_name='Adresse :')),
                ('fonction_poste', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fonction/postale :')),
                ('grade', models.CharField(blank=True, choices=[('Assistant', 'Assistant'), ('Maître assistant', 'Maître assistant'), ('Maître de conférences', 'Maître de conférences'), ('Professeur', 'Professeur'), ('Autre', 'Autre')], max_length=150, null=True, verbose_name='Grade :')),
                ('specialite', models.CharField(blank=True, choices=[('Informatique', 'Informatique'), ('Biologie', 'Biologie'), ('Chimie', 'Chimie'), ('Physique', 'Physique'), ('Mathématiques', 'Mathématiques'), ('Médecine', 'Médecine'), ('Autre', 'Autre')], max_length=150, null=True, verbose_name='Spécialité :')),
                ('orcid', models.CharField(blank=True, max_length=150, null=True, verbose_name='ORCID :')),
                ('role', models.CharField(blank=True, choices=[('auteur', 'Auteur'), ('relecteur', 'Relecteur'), ('visiteur', 'Visiteur'), ('admin', 'Administrateur')], max_length=150, null=True, verbose_name='Rôle :')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='accounts', verbose_name='Photo :')),
                ('reseau_social_facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('reseau_social_twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('reseau_social_linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('reseau_social_youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustumerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('prenoms', models.CharField(max_length=150, verbose_name='Prénom(s) :')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom :')),
                ('sexe', models.CharField(blank=True, choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=150, null=True, verbose_name='Sexe :')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email :')),
                ('tel', models.CharField(max_length=20, unique=True, verbose_name='Téléphone :')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biographie', models.TextField(blank=True, null=True, verbose_name='Biographie :')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biography', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_etude_academique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etude_academique', models.TextField(blank=True, null=True, verbose_name='Etude académique :')),
                ('date_debut_etude', models.DateField(blank=True, null=True, verbose_name='Date de début :')),
                ('date_fin_etude', models.DateField(blank=True, null=True, verbose_name='Date de fin :')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etude_academique', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_experience_professionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_professionnelle', models.TextField(blank=True, null=True, verbose_name='Expérience professionnelle :')),
                ('date_debut_experience', models.DateField(blank=True, null=True, verbose_name='Date de début :')),
                ('date_fin_experience', models.DateField(blank=True, null=True, verbose_name='Date de fin :')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experience_professionnelle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
