# Generated by Django 5.2 on 2025-06-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustumerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(blank=True, max_length=150, null=True, verbose_name='Prénoms :')),
                ('prenoms', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom :')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=150, null=True, verbose_name='Adresse :')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email :')),
                ('tel', models.CharField(blank=True, max_length=150, null=True, verbose_name='Téléphone:')),
                ('profession', models.CharField(blank=True, max_length=150, null=True, verbose_name='Profession :')),
                ('sexe', models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('feminin', 'Féminin')], max_length=150, null=True, verbose_name='Sexe :')),
                ('matricule', models.CharField(blank=True, max_length=150, null=True, verbose_name='Matricule :')),
                ('role', models.CharField(blank=True, choices=[('administrateur', 'Administrateur'), ('agent', 'Agent')], max_length=150, null=True, verbose_name='Rôle :')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='accounts', verbose_name='Photo :')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
