# Generated by Django 5.2 on 2025-06-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumeruser',
            name='nom',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom :'),
        ),
        migrations.AlterField(
            model_name='custumeruser',
            name='prenoms',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Prénoms :'),
        ),
    ]
