# Generated by Django 5.2 on 2026-05-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('enseignant', 'Enseignant'), ('enseignant chercheur', 'Enseignant chercheur'), ('responsable institution', "Responsable d'institution")], max_length=150, null=True, verbose_name='Rôle :'),
        ),
    ]
