# Generated by Django 5.2 on 2026-07-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('Docteur', 'Docteur'), ('Assistant', 'Assistant'), ('Maître assistant', 'Maître assistant'), ('Maître de conférences', 'Maître de conférences'), ('Professeur', 'Professeur'), ('Autre', 'Autre')], max_length=150, null=True, verbose_name='Grade :'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialite',
            field=models.CharField(blank=True, choices=[('Informatique', 'Informatique'), ('Biologie', 'Biologie'), ('Chimie', 'Chimie'), ('Physique', 'Physique'), ('Mathématiques', 'Mathématiques'), ('Médecine', 'Médecine'), ('Agronomie', 'Agronomie'), ('Génie Civil', 'Génie Civil'), ('Génie Industriel', 'Génie Industriel'), ('Génie Logiciel', 'Génie Logiciel'), ('Génie Mathématique', 'Génie Mathématique'), ('Génie Physique', 'Génie Physique'), ('Génie Chimie', 'Génie Chimie'), ('Génie Biologique', 'Génie Biologique'), ('Génie Agronomique', 'Génie Agronomique'), ('Sciences Sociales', 'Sciences Sociales'), ('Sciences de la Vie', 'Sciences de la Vie'), ('Sciences de la Terre', 'Sciences de la Terre'), ("Sciences de l'Education", "Sciences de l'Education"), ('Sciences de la Santé', 'Sciences de la Santé'), ('Sciences de la Culture', 'Sciences de la Culture'), ('Sciences de la Communication', 'Sciences de la Communication'), ('Sciences de la Politique', 'Sciences de la Politique'), ('Sciences de la Religion', 'Sciences de la Religion'), ('Autre', 'Autre')], max_length=150, null=True, verbose_name='Spécialité :'),
        ),
    ]
