# Generated by Django 5.2 on 2025-06-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_custumeruser_nom_alter_custumeruser_prenoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumeruser',
            name='prenoms',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Prénom(s) :'),
        ),
        migrations.AlterField(
            model_name='custumeruser',
            name='role',
            field=models.CharField(blank=True, choices=[('visiteur', 'Visiteur'), ('auteur', 'Auteur'), ('administrateur', 'Administrateur')], max_length=150, null=True, verbose_name='Rôle :'),
        ),
    ]
