# Generated by Django 5.2 on 2026-04-14 13:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_etude_academique',
            name='etude_academique',
        ),
        migrations.RemoveField(
            model_name='user_experience_professionnelle',
            name='experience_professionnelle',
        ),
        migrations.AddField(
            model_name='user_biography',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_biography',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publié :'),
        ),
        migrations.AddField(
            model_name='user_biography',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user_etude_academique',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_etude_academique',
            name='departement_etude',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Département :'),
        ),
        migrations.AddField(
            model_name='user_etude_academique',
            name='diplome_obtenu',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Diplôme obtenu :'),
        ),
        migrations.AddField(
            model_name='user_etude_academique',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publié :'),
        ),
        migrations.AddField(
            model_name='user_etude_academique',
            name='nom_institution',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom de l'institution :"),
        ),
        migrations.AddField(
            model_name='user_etude_academique',
            name='pays_institution',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Pays de l'institution :"),
        ),
        migrations.AddField(
            model_name='user_etude_academique',
            name='region_institution',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Région de l'institution :"),
        ),
        migrations.AddField(
            model_name='user_etude_academique',
            name='type_formation',
            field=models.CharField(blank=True, choices=[('Academique', 'Académique'), ('Attestation', 'Attestation'), ('Certification', 'Certification'), ('Professionnelle', 'Professionnelle')], max_length=150, null=True, verbose_name='Type de formation :'),
        ),
        migrations.AddField(
            model_name='user_etude_academique',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user_etude_academique',
            name='ville_institution',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Ville de l'institution :"),
        ),
        migrations.AddField(
            model_name='user_experience_professionnelle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_experience_professionnelle',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publié :'),
        ),
        migrations.AddField(
            model_name='user_experience_professionnelle',
            name='nom_institution',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom de l'institution :"),
        ),
        migrations.AddField(
            model_name='user_experience_professionnelle',
            name='poste_occupe',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Poste occupé :'),
        ),
        migrations.AddField(
            model_name='user_experience_professionnelle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user_biography',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biographie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('masterant', 'Masterant'), ('doctorant', 'Doctorant'), ('encadreur', 'Encadreur'), ('enseignant', 'Enseignant'), ('enseignant chercheur', 'Enseignant chercheur'), ('responsable institution', "Responsable d'institution"), ('admin', 'Administrateur')], max_length=150, null=True, verbose_name='Rôle :'),
        ),
        migrations.CreateModel(
            name='User_emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_institution', models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom de l'institution :")),
                ('ville_emploi', models.CharField(blank=True, max_length=150, null=True, verbose_name="Ville de l'emploi :")),
                ('region_emploi', models.CharField(blank=True, max_length=150, null=True, verbose_name="Région de l'emploi :")),
                ('pays_emploi', models.CharField(blank=True, max_length=150, null=True, verbose_name="Pays de l'emploi :")),
                ('departement_emploi', models.CharField(blank=True, max_length=150, null=True, verbose_name='Département :')),
                ('poste_occupe', models.CharField(blank=True, max_length=150, null=True, verbose_name='Poste occupé :')),
                ('date_debut_emploi', models.DateField(blank=True, null=True, verbose_name='Date de début :')),
                ('date_fin_emploi', models.DateField(blank=True, null=True, verbose_name='Date de fin :')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié :')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emploi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_travaux_recherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_institution', models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom de l'institution :")),
                ('ville_institution', models.CharField(blank=True, max_length=150, null=True, verbose_name="Ville de l'institution :")),
                ('region_institution', models.CharField(blank=True, max_length=150, null=True, verbose_name="Région de l'institution :")),
                ('pays_institution', models.CharField(blank=True, max_length=150, null=True, verbose_name="Pays de l'institution :")),
                ('departement_recherche', models.CharField(blank=True, max_length=150, null=True, verbose_name='Département de recherche :')),
                ('poste_occupe', models.CharField(blank=True, max_length=150, null=True, verbose_name='Poste occupé :')),
                ('titre_domaine_recherche', models.CharField(blank=True, max_length=150, null=True, verbose_name='Titre/Domaine :')),
                ('date_de_debut_travaux', models.DateField(blank=True, null=True, verbose_name='Date de début :')),
                ('date_de_fin_travaux', models.DateField(blank=True, null=True, verbose_name='Date de fin :')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié :')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travaux_recherche', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
