# Generated by Django 5.2 on 2026-07-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_grade_alter_userprofile_specialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='orcid',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ORCID :'),
        ),
    ]
