# Generated by Django 5.2 on 2026-06-15 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_emploi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emploi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_etude_academique',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etude_academique', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_experience_professionnelle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_professionnelle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_travaux_recherche',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travaux_recherche', to=settings.AUTH_USER_MODEL),
        ),
    ]
