# Generated by Django 5.2 on 2025-06-27 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_custumeruser_prenoms_alter_custumeruser_role'),
        ('institutions', '0002_alter_institution_nom_alter_institution_pays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumeruser',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution', verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='custumeruser',
            name='orcid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Orcid'),
        ),
        migrations.AddField(
            model_name='custumeruser',
            name='statut_auteur',
            field=models.CharField(choices=[('Enseignant', 'Enseignant'), ('Doctorant', 'Doctorant'), ('Chercheur', 'Chercheur'), ('Autre', 'Autre')], default=django.utils.timezone.now, max_length=50, verbose_name='Statut'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custumeruser',
            name='statut_user',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Statut :'),
        ),
    ]
