# Generated by Django 5.2 on 2025-06-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_custumeruser_institution_custumeruser_orcid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custumeruser',
            name='statut_user',
        ),
        migrations.AlterField(
            model_name='custumeruser',
            name='role',
            field=models.CharField(blank=True, choices=[('administrateur', 'Administrateur'), ('super_administrateur', 'Super administrateur')], max_length=150, null=True, verbose_name='Rôle :'),
        ),
    ]
