# Generated by Django 5.2 on 2025-06-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_custumeruser_statut_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumeruser',
            name='role',
            field=models.CharField(blank=True, choices=[('auteur', 'Auteur'), ('administrateur', 'administrateur')], max_length=150, null=True, verbose_name='Rôle :'),
        ),
    ]
