# Generated by Django 5.2 on 2025-07-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_custumeruser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custumeruser',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='custumeruser',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='custumeruser',
            name='orcid',
        ),
        migrations.RemoveField(
            model_name='custumeruser',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='custumeruser',
            name='statut_auteur',
        ),
        migrations.AlterField(
            model_name='custumeruser',
            name='role',
            field=models.CharField(blank=True, choices=[('auteur', 'Auteur'), ('relecteur', 'Relecteur'), ('visiteur', 'Visiteur'), ('admin', 'Administrateur')], max_length=150, null=True, verbose_name='Rôle :'),
        ),
    ]
