# Generated by Django 5.2 on 2025-07-02 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0003_institution_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encadreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenoms', models.CharField(max_length=100, verbose_name='Prénom(s)')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('grade', models.CharField(choices=[('Professeur', 'Professeur'), ('Maître de conférences', 'Maître de conférences'), ('Docteur', 'Docteur'), ('Autre', 'Autre')], default='Autre', max_length=100, verbose_name='Grade')),
                ('specialite', models.CharField(help_text='Ex: Intelligence Artificielle, Biologie moléculaire...', max_length=200, verbose_name='Spécialité')),
                ('parcours', models.TextField(blank=True, help_text='Résumé du parcours académique et professionnel', verbose_name='Parcours')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='encadreurs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution', verbose_name='Institution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'encadreur',
                'verbose_name_plural': 'encadreurs',
                'db_table': 'encadreur',
            },
        ),
    ]
