# Generated by Django 5.2 on 2025-07-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encadreurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encadreur',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encadreur',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encadreur',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encadreur',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='encadreurs/photos/'),
        ),
    ]
