# Generated by Django 5.2 on 2026-05-11 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='publicatons/photos', verbose_name='Photo :')),
                ('titre', models.CharField(blank=True, max_length=300, null=True, verbose_name='Titre')),
                ('type_publication', models.CharField(choices=[('article', 'Article scientifique'), ('colloque', 'Communication de Colloque')], default='', max_length=50, verbose_name='Type du publication')),
                ('domaine', models.CharField(blank=True, max_length=100, null=True, verbose_name='Domaine')),
                ('fichier_pdf', models.FileField(upload_to='publications/fichiers', verbose_name='Fichier')),
                ('langue', models.CharField(default='français', max_length=50, verbose_name='Langue')),
                ('doi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Doi')),
                ('statut_indexation', models.CharField(choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Rejetée', 'Rejetée')], default='En attente', max_length=50, verbose_name='Statut indexation')),
                ('motif_rejet', models.TextField(blank=True, null=True, verbose_name='Motif rejet')),
                ('mots_cles', models.TextField(blank=True, null=True, verbose_name='Mots cles')),
                ('resume', models.TextField(blank=True, null=True, verbose_name='Resumé')),
                ('statut_publication', models.BooleanField(default=False)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('date_ajout_systeme', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
                'db_table': 'publication',
            },
        ),
        migrations.CreateModel(
            name='ArticleScientifique',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.publication')),
                ('nom_revue', models.CharField(max_length=225)),
                ('lien_article', models.URLField(blank=True, max_length=500, null=True, verbose_name="Lien de l'article")),
                ('facteur_impact', models.FloatField(blank=True, null=True)),
            ],
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='Colloque',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.publication')),
                ('nom_colloque', models.CharField(max_length=225)),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('date_colloque', models.DateField(blank=True, null=True)),
            ],
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='PublicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publications.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publicationComment',
            },
        ),
        migrations.CreateModel(
            name='PublicationDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='publications.publication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publicationDownload',
            },
        ),
        migrations.CreateModel(
            name='PublicationAuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=30)),
                ('ordre', models.PositiveIntegerField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('publication', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='PublicationLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='publications.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publicationLike',
                'unique_together': {('publication', 'user')},
            },
        ),
    ]
