# Generated by Django 5.2 on 2025-06-11 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auteurs', '0001_initial'),
        ('institutions', '0001_initial'),
        ('types_document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('resume', models.TextField()),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('date_publication', models.DateField()),
                ('fichier_pdf', models.FileField(upload_to='publications/')),
                ('langue', models.CharField(default='français', max_length=50)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('orcid_auteur_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('date_ajout_systeme', models.DateTimeField(auto_now_add=True)),
                ('statut_indexation', models.CharField(choices=[('En attente', 'En attente'), ('Indexée', 'Indexée'), ('Rejetée', 'Rejetée')], default='En attente', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteurs', models.ManyToManyField(to='auteurs.auteur')),
                ('institutions_contributrices', models.ManyToManyField(related_name='publications_contribuees', to='institutions.institution')),
                ('type_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='types_document.typedocument')),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
                'db_table': 'publication',
            },
        ),
    ]
