# Generated by Django 5.2 on 2026-05-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='texte_integral',
            field=models.TextField(blank=True, null=True, verbose_name='Texte intégral'),
        ),
        migrations.AddField(
            model_name='publication',
            name='texte_nettoye',
            field=models.TextField(blank=True, null=True, verbose_name='Texte nettoyé'),
        ),
    ]
