# Generated by Django 5.2 on 2025-06-23 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auteurs', '0002_alter_auteur_email_alter_auteur_institution_and_more'),
        ('institutions', '0002_alter_institution_nom_alter_institution_pays_and_more'),
        ('publications', '0001_initial'),
        ('types_document', '0002_alter_typedocument_libelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='publication',
            name='auteurs',
            field=models.ManyToManyField(to='auteurs.auteur', verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_publication',
            field=models.DateField(verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doi'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='fichier_pdf',
            field=models.FileField(upload_to='publications/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='institutions_contributrices',
            field=models.ManyToManyField(related_name='publications_contribuees', to='institutions.institution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='langue',
            field=models.CharField(default='français', max_length=50, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='orcid_auteur_principal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Orci'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='resume',
            field=models.TextField(verbose_name='Resumé'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='statut_indexation',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Indexée', 'Indexée'), ('Rejetée', 'Rejetée')], default='En attente', max_length=50, verbose_name='Statut indexation'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='titre',
            field=models.CharField(max_length=300, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='types_document.typedocument', verbose_name='Type du document'),
        ),
    ]
