# Generated by Django 5.2 on 2026-07-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='bases_indexation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Bases d'indexation"),
        ),
    ]
