# Generated by Django 5.2 on 2026-05-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_texte_integral_publication_texte_nettoye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='langue',
            field=models.CharField(blank=True, default='français', max_length=50, verbose_name='Langue'),
        ),
    ]
