# Generated by Django 5.2 on 2025-06-27 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_remove_publication_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='auteurs',
            field=models.ManyToManyField(related_name='publications', to=settings.AUTH_USER_MODEL),
        ),
    ]
