# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_add_bases_indexation'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='licence',
            field=models.CharField(
                blank=True,
                choices=[
                    ('CC-BY-4.0', 'CC BY 4.0 — Attribution'),
                    ('CC-BY-SA-4.0', "CC BY-SA 4.0 — Attribution, Partage à l'identique"),
                    ('CC-BY-NC-4.0', "CC BY-NC 4.0 — Pas d'utilisation commerciale"),
                    ('CC-BY-NC-SA-4.0', 'CC BY-NC-SA 4.0'),
                    ('CC-BY-ND-4.0', 'CC BY-ND 4.0 — Pas de modification'),
                    ('CC-BY-NC-ND-4.0', 'CC BY-NC-ND 4.0'),
                    ('tous-droits-reserves', 'Tous droits réservés'),
                ],
                default='CC-BY-4.0',
                max_length=40,
                verbose_name='Licence',
            ),
        ),
    ]
