# Generated by Django 5.2 on 2025-07-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_auteurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='orcid_auteur_principal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Orcid'),
        ),
    ]
