# Generated by Django 5.2 on 2026-08-25 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets_detudes', '0002_message_chat'),
        ('publications', '0003_publication_licence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='type_publication',
            field=models.CharField(choices=[('article', 'Article scientifique'), ('colloque', 'Communication de Colloque'), ('memoire', 'Mémoire'), ('these', 'Thèse')], default='', max_length=50, verbose_name='Type du publication'),
        ),
        migrations.CreateModel(
            name='ProjetPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets_detudes.projetetude')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication')),
            ],
        ),
    ]
