# Generated by Django 5.2 on 2025-07-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auteurs', '0003_auteur_user'),
        ('encadreurs', '0001_initial'),
        ('publications', '0005_publication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='encadreurs',
            field=models.ManyToManyField(to='encadreurs.encadreur', verbose_name='Encadreur(s)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='auteurs',
            field=models.ManyToManyField(to='auteurs.auteur', verbose_name='Auteur(s)'),
        ),
    ]
