# Generated by Django 5.2 on 2025-07-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_institution_user'),
        ('publications', '0006_publication_encadreurs_alter_publication_auteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='domaine',
            field=models.CharField(blank=True, max_length=100, verbose_name='Domaine'),
        ),
        migrations.AddField(
            model_name='publication',
            name='mots_cles',
            field=models.TextField(blank=True, verbose_name='Mots cles'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='institutions_contributrices',
            field=models.ManyToManyField(related_name='publications_contribuees', to='institutions.institution', verbose_name='Institution(s)'),
        ),
    ]
