# Generated by Django 5.2 on 2025-07-11 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_publication_domaine_publication_mots_cles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True, verbose_name='Motif rejet'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Doi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='orcid_auteur_principal',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Orcid'),
            preserve_default=False,
        ),
    ]
