# Generated by Django 5.2 on 2025-07-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_publication_motif_rejet_alter_publication_doi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='publicatons/photos', verbose_name='Photo :'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='fichier_pdf',
            field=models.FileField(upload_to='publications/fichiers', verbose_name='Fichier'),
        ),
    ]
