# Generated by Django 5.2 on 2025-07-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_publication_photo_alter_publication_fichier_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='statut_publication',
            field=models.BooleanField(default=False),
        ),
    ]
