# Generated by Django 5.2 on 2025-07-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auteurs', '0006_alter_auteur_prenoms'),
        ('encadreurs', '0002_encadreur_facebook_encadreur_linkedin_and_more'),
        ('institutions', '0003_institution_user'),
        ('publications', '0011_publicationcomment_publicationdownload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='lien_article',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="Lien de l'article"),
        ),
        migrations.AddField(
            model_name='publication',
            name='nom_colloque',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Nom du colloque'),
        ),
        migrations.AddField(
            model_name='publication',
            name='nom_revue',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Nom de la revue'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='auteurs',
            field=models.ManyToManyField(blank=True, null=True, to='auteurs.auteur', verbose_name='Auteur(s)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_publication',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doi'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='domaine',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domaine'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='encadreurs',
            field=models.ManyToManyField(blank=True, null=True, to='encadreurs.encadreur', verbose_name='Encadreur(s)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='institutions_contributrices',
            field=models.ManyToManyField(blank=True, null=True, related_name='publications_contribuees', to='institutions.institution', verbose_name='Institution(s)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='orcid_auteur_principal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Orcid'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='resume',
            field=models.TextField(blank=True, null=True, verbose_name='Resumé'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='titre',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Titre'),
        ),
    ]
