# Generated by Django 5.2 on 2026-05-11 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/logos/', verbose_name='Logo')),
                ('site_web', models.URLField(blank=True, verbose_name='Site Web')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('is_actif', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
