# Generated by Django 5.2 on 2025-07-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partenaire',
            old_name='actif',
            new_name='is_actif',
        ),
    ]
