# Generated by Django 5.2 on 2025-07-23 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='prenoms',
        ),
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='nom_complet',
            field=models.CharField(default=django.utils.timezone.now, max_length=225, verbose_name='Nom complet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='detail',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='objectif',
            field=models.CharField(max_length=255, verbose_name='Objet'),
        ),
    ]
