# Generated by Django 5.2 on 2025-07-23 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_remove_contactus_nom_remove_contactus_prenoms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='detail',
            new_name='message',
        ),
        migrations.AddField(
            model_name='contactus',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactus',
            name='reponse_au_message',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Message'),
            preserve_default=False,
        ),
    ]
