# Generated by Django 5.2 on 2025-07-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_rename_detail_contactus_message_contactus_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='reponse_au_message',
            field=models.TextField(verbose_name='Reponse'),
        ),
    ]
