# Generated by Django 5.2 on 2026-05-11 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indexation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('date_indexation', models.DateTimeField(auto_now_add=True)),
                ('mots_cles_ai', models.TextField()),
                ('resume_ia', models.TextField()),
                ('score_pertinence', models.FloatField()),
                ('outil_indexation', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publications.publication')),
            ],
            options={
                'verbose_name': 'indexation',
                'verbose_name_plural': 'indexations',
                'db_table': 'indexation',
            },
        ),
    ]
