# Generated by Django 5.2 on 2026-08-25 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexations', '0001_initial'),
        ('publications', '0003_publication_licence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexation',
            name='mots_cles_ai',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='indexation',
            name='outil_indexation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='indexation',
            name='publication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indexation', to='publications.publication'),
        ),
        migrations.AlterField(
            model_name='indexation',
            name='resume_ia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='indexation',
            name='score_pertinence',
            field=models.FloatField(default=0),
        ),
    ]
