# Generated by Django 5.2 on 2026-07-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('resume', models.TextField(help_text='Court texte affiché sur la page d’accueil.', max_length=500, verbose_name='Résumé')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/images/', verbose_name='Image')),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_actif', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'db_table': 'actualite',
                'ordering': ['-date_publication', '-created_at'],
            },
        ),
    ]
