# Generated by Django 5.2 on 2026-04-09 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('nb_vues', models.PositiveIntegerField(default=0)),
                ('nb_telechargements', models.PositiveIntegerField(default=0)),
                ('partages', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publications.publication')),
            ],
            options={
                'verbose_name': 'statistique',
                'verbose_name_plural': 'statistiques',
                'db_table': 'statistique',
            },
        ),
    ]
