# Generated by Django 5.2 on 2026-04-09 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_institution', models.CharField(blank=True, choices=[('Université', 'Université'), ('Centre de recherche', 'Centre de recherche')], max_length=50, null=True, verbose_name='Type')),
                ('nom_institution', models.CharField(max_length=255, verbose_name="Nom de l'Institution")),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('sigle_institution', models.CharField(max_length=20, verbose_name="Sigle de l'Institution")),
                ('email_institution', models.EmailField(max_length=254, verbose_name="Email de l'Institution")),
                ('telephone_institution', models.CharField(default=0, max_length=20, verbose_name="Téléphone de l'Institution")),
                ('adresse_institution', models.CharField(max_length=30, verbose_name="Adresse de l'Institution")),
                ('ville', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ville')),
                ('pays', models.CharField(blank=True, default='Guinée', max_length=20, null=True, verbose_name='Pays')),
                ('site_web_institution', models.URLField(verbose_name='Site web')),
                ('logo_institution', models.ImageField(blank=True, null=True, upload_to='institutions/logos/', verbose_name="Logo de l'Institution")),
                ('reseau_social_facebook_inst', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('reseau_social_twitter_inst', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('reseau_social_linkedin_inst', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('reseau_social_youtube_inst', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'institution',
                'verbose_name_plural': 'institutions',
                'db_table': 'institution',
            },
        ),
    ]
