# Generated by Django 5.2 on 2025-06-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('type', models.CharField(choices=[('Université', 'Université'), ('Centre de recherche', 'Centre de recherche')], max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Guinée', max_length=100)),
                ('site_web', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'institution',
                'verbose_name_plural': 'institutions',
                'db_table': 'institution',
            },
        ),
    ]
