# Generated by Django 5.2 on 2026-07-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='ror',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ROR'),
        ),
    ]
