# Generated by Django 5.2 on 2025-06-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='nom',
            field=models.CharField(max_length=255, verbose_name="Nom de l'Institution"),
        ),
        migrations.AlterField(
            model_name='institution',
            name='pays',
            field=models.CharField(default='Guinée', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='site_web',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('Université', 'Université'), ('Centre de recherche', 'Centre de recherche')], max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='ville',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
    ]
