# Generated by Django 5.2 on 2025-07-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_nom_remove_notification_prenoms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_statut',
            field=models.BooleanField(default=False),
        ),
    ]
