# Generated by Django 5.2 on 2025-06-11 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('orcid', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('Enseignant', 'Enseignant'), ('Doctorant', 'Doctorant'), ('Chercheur', 'Chercheur'), ('Autre', 'Autre')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution')),
            ],
            options={
                'verbose_name': 'auteur',
                'verbose_name_plural': 'auteurs',
                'db_table': 'auteur',
            },
        ),
    ]
