# Generated by Django 5.2 on 2026-04-09 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='auteurs/photos/')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=100, verbose_name='Prénom(s)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('orcid', models.CharField(blank=True, max_length=50, null=True, verbose_name='Orcid')),
                ('statut', models.CharField(choices=[('Enseignant', 'Enseignant'), ('Doctorant', 'Doctorant'), ('Chercheur', 'Chercheur'), ('Autre', 'Autre')], max_length=50, verbose_name='Statut')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('biographie', models.TextField(blank=True, help_text='Résumé du parcours académique et professionnel', null=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution', verbose_name='Institution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'auteur',
                'verbose_name_plural': 'auteurs',
                'db_table': 'auteur',
            },
        ),
    ]
