# Generated by Django 5.2 on 2025-06-20 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auteurs', '0001_initial'),
        ('institutions', '0002_alter_institution_nom_alter_institution_pays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='orcid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Orcid'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='prenoms',
            field=models.CharField(max_length=100, verbose_name='Prénoms'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='statut',
            field=models.CharField(choices=[('Enseignant', 'Enseignant'), ('Doctorant', 'Doctorant'), ('Chercheur', 'Chercheur'), ('Autre', 'Autre')], max_length=50, verbose_name='Statut'),
        ),
    ]
