# Generated by Django 5.2 on 2025-07-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auteurs', '0003_auteur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='biographie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auteur',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auteur',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auteur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='auteurs/photos/'),
        ),
        migrations.AddField(
            model_name='auteur',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auteur',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
