# Generated by Django 5.2 on 2025-07-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auteurs', '0004_auteur_biographie_auteur_facebook_auteur_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='biographie',
            field=models.TextField(blank=True, help_text='Résumé du parcours académique et professionnel', null=True),
        ),
    ]
