# Generated by Django 5.2 on 2025-07-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auteurs', '0005_alter_auteur_biographie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='prenoms',
            field=models.CharField(max_length=100, verbose_name='Prénom(s)'),
        ),
    ]
